Add edid override for AYANEO GEEK.
ChimeraOS/device-quirks pull request #54
Opened 2023-06-26 12:06 UTC by oliverchang

This fixes an edid parse failure by patching out a bad section in the edid, and seems to fix
https://github.com/ValveSoftware/gamescope/issues/864.

The diff for me is: 
```
9c9
< 00000080: 0203 1030 d050 2000 2e50 200a a001 71b5  ...0.P ..P ...q.
---
> 00000080: 0203 1030 cb50 2000 2e50 200a a001 71b5  ...0.P ..P ...q.
16c16
< 000000f0: 0000 0000 0000 0000 0000 0000 0000 0056  ...............V
---
> 000000f0: 0000 0000 0000 0000 0000 0000 0000 005b  ...............[
```

2023-06-26 12:09 UTC, Samsagax requested changes

2023-06-26 12:10 UTC, oliverchang commented
Note there are AYANEO GEEK devices out there with a 1200p panel (I believe the same as the AYANEO 2) instead of the default 800p panel which I have. I'm not sure how to distinguish those at this point though.

Perhaps we could check the original edid shasum and only patch in that case? Is that available in the context where this script runs?

2023-06-26 12:10 UTC, oliverchang commented on usr/share/device-quirks/scripts/ayaneo/ayaneo_table.sh
> +  if [[ "GEEK" == "$PRODUCT_NAME" ]]; then
Hmm, I'm doing a direct match here using ==. Is that still necessary?

2023-06-26 12:10 UTC, oliverchang commented
CC @ruineka too :)

2023-06-26 13:04 UTC, pastaq commented on usr/share/device-quirks/scripts/ayaneo/ayaneo_table.sh
> +  if [[ "GEEK" == "$PRODUCT_NAME" ]]; then
If we're going to do this then I'd prefer to have a PRODUCT_LIST_GEEK and remove geek from the 2 list. Add the audio quirk to the geek.sh the 2.sh has.

2023-06-26 13:11 UTC, ruineka commented
We might be having a proper fix underway soon. Don't merge this unless we have too.

2023-07-02 01:18 UTC, oliverchang commented
https://gitlab.freedesktop.org/emersion/libdisplay-info/-/merge_requests/164 is the code workaround that will fix this particular instance.

2023-07-02 01:43 UTC, ruineka commented
> https://gitlab.freedesktop.org/emersion/libdisplay-info/-/merge_requests/164 is the code workaround that will fix this particular instance.

Indeed it is, any chance you can comment under there where it's asking about permission to list the EDID under MIT? I added my EDID as well but they used yours as the sample to be used.

2023-09-13 21:18 UTC, pastaq commented
has there been any movement on the patch for this, or a way to ID the 800P display units only?

2024-03-29 23:52 UTC, closed without merging