Added refind support
ChimeraOS/device-quirks pull request #96
Opened 2024-02-05 08:01 UTC by Boria138

2024-02-05 23:06 UTC, pastaq commented
A lot of folks use refind when the manually enable dual booting so I don;t have an issue with this. This wont affect regular users in any way?

2024-02-05 23:08 UTC, pastaq requested changes
Minor readability/style fixes.

2024-02-05 23:08 UTC, pastaq commented on usr/share/device-quirks/scripts/kernel-options-manager
> +                then sed -i "s/rw/rw $search_string/" "$entry_file"
Can you ensure consistent styling here?

2024-02-05 23:08 UTC, pastaq commented on usr/share/device-quirks/scripts/kernel-options-manager
> +        then grep "^\"$options\"" "$entry_file" | sed 's/^\"'"$options"'" //' | sed 's/\s*$//' | tr ' ' '\n'
Also here.

2024-02-05 23:15 UTC, alkazar commented
Not sure I understand the purpose of this. Maybe I don't understand refind. I thought it just basically chainloads. Why does it need to have its own kernel parameters?

2024-02-07 00:37 UTC, pastaq commented
LGTM, and if it has no negative effect on others then what's the problem?

from the arch wiki:
```
After installing rEFInd's files to the ESP, verify that rEFInd has created refind_linux.conf containing [kernel parameters](https://wiki.archlinux.org/title/Kernel_parameters) in the same directory as your kernel. This configuration file will not be created if you used the --usedefault option, run mkrlconf as root to create it.
Warning: When refind-install is run in chroot (e.g. in live system when installing Arch Linux) /boot/refind_linux.conf is populated with kernel options from the live system not the one on which it is installed. Edit /boot/refind_linux.conf and make sure the [kernel parameters](https://wiki.archlinux.org/title/Kernel_parameters) in it are correct for your system, otherwise you could get a kernel panic on your next boot. See [#refind_linux.conf](https://wiki.archlinux.org/title/REFInd#refind_linux.conf) for an example file.
```

2024-02-07 00:38 UTC, pastaq approved these changes

2024-03-31 13:32 UTC, alkazar commented
There is an upcoming refactor that will also cover this case.

2024-03-31 13:32 UTC, closed without merging